"""empty message

Revision ID: 737b2381bfa7
Revises: 
Create Date: 2020-06-05 15:45:06.940734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737b2381bfa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.Column('category_description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=64), nullable=True),
    sa.Column('user_username', sa.String(length=64), nullable=True),
    sa.Column('user_role', sa.String(length=10), nullable=True),
    sa.Column('user_first_name', sa.String(length=64), nullable=True),
    sa.Column('user_last_name', sa.String(length=64), nullable=True),
    sa.Column('user_birthday', sa.DateTime(), nullable=True),
    sa.Column('user_date', sa.DateTime(), nullable=True),
    sa.Column('user_location', sa.String(length=64), nullable=True),
    sa.Column('user_about', sa.String(length=140), nullable=True),
    sa.Column('user_occupation', sa.String(length=100), nullable=True),
    sa.Column('user_interests', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_email'), 'user', ['user_email'], unique=True)
    op.create_index(op.f('ix_user_user_role'), 'user', ['user_role'], unique=False)
    op.create_index(op.f('ix_user_user_username'), 'user', ['user_username'], unique=True)
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_author', sa.Integer(), nullable=True),
    sa.Column('topic_title', sa.String(length=100), nullable=True),
    sa.Column('topic_date', sa.DateTime(), nullable=True),
    sa.Column('topic_content', sa.Text(), nullable=True),
    sa.Column('topic_category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['topic_category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('reply_date', sa.DateTime(), nullable=True),
    sa.Column('reply_topic', sa.Integer(), nullable=True),
    sa.Column('reply_author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reply_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reply_topic'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('topic')
    op.drop_index(op.f('ix_user_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('category')
    # ### end Alembic commands ###
